### ISSUE TITLE
question.. how do u compile it  

### ISSUE THREAD

**Issue by a51kot** [noahvogt/ungoogled-chromium-xdg-aur#1]
gow do u compile it
- private vps
- github tools
- opensuse build service

**Comment by noahvogt** [comment]
Currently I build it on a local machine running Artix, but I will consider looking into properly building it in a clean arch chroot environment as to archive reproducability.

**Comment by a51kot** [comment]
could u gave me its specs

_i literally have a 8core cpu (fx 8350) and its SO traumatic  that im now playin with opensuse build service_

**Comment by noahvogt** [comment]
That system has an over 5 y/o intel quad core, ddr3 ram and it takes between six and seven hours to build.

Not sure what you are trying to do, is it anything specific like:
- learning / experimenting with the arch build process
- creating a fork
- repacking
- automate the building of ungoogled chromium
?
